log4cpp_config_file: log4cpp.conf
tun_driver: tun
multithreading_read_send: true
multithreading_write_recv: true
heartbeat_interval: 500
heartbeat_timeout: 9000
tun_read_max: 32
client_id: 7x_client_id
tun_name: tun_abyss
negotiation_server_ip: 127.0.0.1
negotiation_server_port: 1891
transport_protocol: udp
transport_server_ip: 127.0.0.1
transport_server_port: 1892
transport_local_ip: 0.0.0.0
enc_type: aes
fec_mode: force
enable_kcp: false
